#! /bin/sh

killall sxhkd 2> /dev/null
sxhkd &

killall compton 2> /dev/null
compton --config ~/.config/compton/compton.conf &

bspc monitor DVI-I-0 -d 1 2 3 4 5
bspc monitor DVI-D-1 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

polybar -c ~/.config/polybar/config main &
polybar -c ~/.config/polybar/config secondary &

feh --bg-fill ~/Pictures/wallpaper.jpg
