#! /bin/sh


sxhkd &

bspc monitor HDMI2 -d 1 2 3 4 5
bspc monitor VGA1 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

polybar -c ~/.config/polybar/config main &
polybar -c ~/.config/polybar/config secondary &

feh --bg-fill ~/Pictures/wallpaper.jpg
